# Generated by Django 4.0.5 on 2022-07-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ariza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='paymentType',
            field=models.CharField(choices=[('exchange', "Pul O'tqazmalari"), ('cash', "Naqt to'lov"), ('None', 'None')], default='None', max_length=35),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi ariza tashlandi'), ('moderatsiya', 'Moderatsya jarayonida'), ('tasdiqlangan', 'Tasdiqlangan'), ('cancel', 'Bekor qilingan')], default='yangi', max_length=125),
        ),
    ]
